name = "parz"
version = "0.0.2"

description = "A simple parser combinator library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sftsrv", repo = "parz" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
